mutation UpdateProduct($id: String!, $descricao: String, $nome: String!, $quantidade: Int) {
  updateProduct(id: $id, descricao: $descricao, nome: $nome, quantidade: $quantidade) {
    nome
    descricao
    quantidade
    createdAt
  }
}